import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'app_language_preference';

// Translations
const translations = {
  en: {
    // Staff Contact Form
    'form.title': 'Lead Contact Form',
    'form.subtitle': 'Collect potential client information',
    'form.clientManager': 'Client Manager',
    'form.clientManager.placeholder': 'Select client manager',
    'form.fullName': 'Full Name',
    'form.fullName.placeholder': 'Enter full name',
    'form.company': 'Company / Organization',
    'form.company.placeholder': 'Enter company name',
    'form.email': 'Email Address',
    'form.email.placeholder': 'email@example.com',
    'form.phone': 'Phone Number',
    'form.phone.placeholder': '+216 XX XXX XXX',
    'form.profile': 'Contact Profile', // NEW: Profile instead of industry
    'form.profile.placeholder': 'Select profile', // NEW
    'form.zone': 'Geographic Zone',
    'form.zone.placeholder': 'Select region',
    'form.interest': 'Interest During Visit',
    'form.interest.placeholder': 'Describe their interests and needs',
    'form.comments': 'Additional Comments',
    'form.comments.placeholder': 'Any additional notes or observations',
    'form.submit': 'Submit Lead',
    'form.reset': 'Reset Form',
    'form.required': 'Required',
    
    // Contact Profile Options (NEW)
    'profile.engineer': 'Engineer',
    'profile.administrator': 'Administrator',
    'profile.manager': 'Manager',
    'profile.director': 'Director',
    'profile.ceo': 'CEO/Executive',
    'profile.sales': 'Sales/Marketing',
    'profile.it': 'IT Professional',
    'profile.hr': 'HR Professional',
    'profile.finance': 'Finance/Accounting',
    'profile.operations': 'Operations',
    'profile.consultant': 'Consultant',
    'profile.technician': 'Technician',
    'profile.student': 'Student/Researcher',
    'profile.other': 'Other',
    
    // Owner Dashboard - Navigation
    'nav.overview': 'Overview',
    'nav.workers': 'Workers',
    'nav.analytics': 'Analytics',
    'nav.export': 'Data Export',
    'nav.profile': 'Profile',
    'nav.loggedInAs': 'Logged in as',
    
    // Owner Dashboard - Overview Page
    'overview.title': 'Dashboard Overview',
    'overview.subtitle': 'Real-time insights for',
    'overview.totalLeads': 'Total Leads Collected',
    'overview.totalWorkers': 'Total Workers',
    'overview.activeWorkers': 'Active Workers',
    'overview.avgLeads': 'Average Leads per Worker',
    'overview.avgPerWorker': 'Avg. per Worker',
    'overview.recentLeads': 'Recent Leads',
    'overview.currentEvent': 'Current Event',
    'overview.active': 'Active',
    'overview.avg': 'Avg',
    'overview.noLeads': 'No leads collected for this event yet',
    'overview.name': 'Name',
    'overview.contact': 'Contact',
    'overview.company': 'Company',
    'overview.phone': 'Phone',
    'overview.email': 'Email',
    'overview.zone': 'Zone',
    'overview.worker': 'Worker',
    'overview.date': 'Date',
    'overview.collectedBy': 'Collected By',
    'overview.fullName': 'Full Name',
    'overview.clientManager': 'Client Manager',
    'overview.fromCurrentEvent': 'From current event only',
    
    // Workers Management
    'workers.title': 'Workers Management',
    'workers.subtitle': 'Manage your staff workers and their access',
    'workers.addWorker': 'Add Worker',
    'workers.name': 'Name',
    'workers.email': 'Email',
    'workers.status': 'Status',
    'workers.leads': 'leads',
    'workers.leadsCollected': 'Leads Collected',
    'workers.actions': 'Actions',
    'workers.active': 'Active',
    'workers.disabled': 'Disabled',
    'workers.edit': 'Edit',
    'workers.disable': 'Disable',
    'workers.enable': 'Enable',
    'workers.deleteAction': 'Delete',
    'workers.deleteWorker': 'Delete Worker',
    'workers.deleteWarning': 'This action cannot be undone',
    'workers.deleteMessage': 'Are you sure you want to delete',
    'workers.confirmDelete': 'Delete Worker',
    'workers.noWorkers': 'No workers yet',
    'workers.addWorkerTitle': 'Add Worker',
    'workers.editWorkerTitle': 'Edit Worker',
    'workers.password': 'Password',
    'workers.confirmPassword': 'Confirm Password',
    'workers.createWorker': 'Create Worker',
    'workers.updateWorker': 'Update Worker',
    'workers.cancel': 'Cancel',
    'workers.totalWorkers': 'Total Workers',
    'workers.activeWorkers': 'Active Workers',
    'workers.disabledWorkers': 'Disabled Workers',
    'workers.fullName': 'Full Name',
    'workers.emailHelp': 'Leave blank to allow login with name only',
    'workers.errorLoading': 'Failed to load workers',
    'workers.workerAdded': 'Staff worker added successfully!',
    'workers.errorAdding': 'Failed to add worker',
    'workers.workerDisabled': 'Worker disabled',
    'workers.workerEnabled': 'Worker enabled',
    'workers.errorUpdating': 'Failed to update worker status',
    'workers.workerUpdated': 'Worker updated successfully!',
    'workers.workerDeleted': 'Worker deleted successfully!',
    'workers.errorDeleting': 'Failed to delete worker',
    'workers.editWorker': 'Edit Worker',
    'workers.newPassword': 'New Password',
    'workers.emailChangeNote': 'Leave blank to keep current email',
    'workers.passwordChangeNote': 'Leave blank to keep current password',
    'workers.saveChanges': 'Save Changes',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Performance metrics and worker statistics',
    'analytics.leadsOverTime': 'Leads Collected Over Time',
    'analytics.noData': 'No data available yet. Start collecting leads!',
    'analytics.topPerformers': 'Top Performing Staff',
    'analytics.active': 'Active',
    'analytics.disabled': 'Disabled',
    'analytics.leadsCollected': 'leads',
    'analytics.noWorkers': 'No workers yet. Add workers to see performance.',
    'analytics.leadsPerWorker': 'Leads per Worker',
    'analytics.activeOnly': 'Active workers only',
    'analytics.leaderboard': 'Worker Leaderboard',
    'analytics.topPerformer': 'Top Performer',
    'analytics.totalActiveWorkers': 'Total Active Workers',
    'analytics.averagePerformance': 'Average Performance',
    'analytics.currentlyActive': 'Currently active',
    'analytics.leadsPerWorkerMetric': 'Leads per worker',
    'analytics.noActiveWorkers': 'No active workers yet',
    
    // Data Export
    'export.title': 'Data Export',
    'export.subtitle': 'Download your lead data in CSV format',
    'export.exportAll': 'Export All Leads',
    'export.downloadAll': 'Download All',
    'export.exportAllDesc': 'Download all leads collected by your staff for the current event',
    'export.exportByWorker': 'Export by Staff Worker',
    'export.exportByWorkerDesc': 'Filter and download leads collected by a specific staff member',
    'export.selectWorker': 'Select Worker',
    'export.allWorkers': 'All Workers',
    'export.chooseWorker': 'Choose a worker...',
    'export.export': 'Export',
    'export.exporting': 'Exporting...',
    'export.downloadFiltered': 'Download Filtered Data',
    'export.currentEvent': 'Current Event',
    'export.note': 'Note',
    'export.noteDesc': 'CSV files include all lead details: contact information, company data, geographic zone, industry sector, and collection timestamps.',
    'export.errorLoading': 'Failed to load data',
    'export.allExported': 'All leads exported successfully!',
    'export.workerExported': 'Worker data exported successfully!',
    'export.errorExporting': 'Failed to export data',
    'export.exportingCurrentEvent': 'Exporting data from current event only',
    'export.event': 'Event',
    'export.csvContents': 'CSV File Contents',
    'export.csvContentsDesc': 'Exported CSV files will include the following columns:',
    'export.fullName': 'Full Name',
    'export.companyOrg': 'Company / Organization',
    'export.emailAddress': 'Email Address',
    'export.phoneNumber': 'Phone Number',
    'export.industrySector': 'Industry Sector',
    'export.geographicZone': 'Geographic Zone',
    'export.clientManager': 'Client Manager',
    'export.interestDuringVisit': 'Interest During Visit',
    'export.comments': 'Comments',
    'export.collectedByWorker': 'Collected By (Staff Worker)',
    'export.collectionDateTime': 'Collection Date & Time',
    'export.historicalData': 'Historical Data Access',
    'export.historicalDataDesc': 'You can only export data from the current event. Historical data from previous events is archived and only accessible to Super Administrators.',
    'export.leads': 'leads',
    
    // Profile/Settings
    'profile.title': 'Profile Settings',
    'profile.subtitle': 'Manage your account information and company branding',
    'profile.languageSettings': 'Language Settings',
    'profile.languageDescription': 'Choose language for your workers\' contact form',
    'profile.personalInfo': 'Personal Information',
    'profile.personalInfoDescription': 'Update your account details',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email Address',
    'profile.emailAddress': 'Email Address',
    'profile.emailNote': 'Email cannot be changed',
    'profile.changePassword': 'Change Password (Optional)',
    'profile.newPassword': 'New Password',
    'profile.confirmNewPassword': 'Confirm New Password',
    'profile.leaveBlankPassword': 'Leave blank to keep current password',
    'profile.confirmPasswordPlaceholder': 'Confirm new password',
    'profile.saveChanges': 'Save Changes',
    'profile.companyInfo': 'Company Information',
    'profile.companyName': 'Company Name',
    'profile.companyBranding': 'Company Branding',
    'profile.companyBrandingDescription': 'Customize your company logo (appears on staff contact forms)',
    'profile.companyLogo': 'Company Logo',
    'profile.companyBackground': 'Contact Form Background',
    'profile.noLogoUploaded': 'No logo uploaded',
    'profile.noBackgroundUploaded': 'No background image uploaded',
    'profile.uploadCompanyLogo': 'Upload Company Logo',
    'profile.uploadBackground': 'Upload Background Image',
    'profile.logoRecommendation': 'Recommended: Square image, minimum 200x200px, JPG/PNG/WebP format, max 5MB',
    'profile.logoHelp': 'This logo will appear on the staff contact form splash screen',
    'profile.backgroundRecommendation': 'Recommended: 1920x1080px or larger, JPG/PNG/WebP format, max 5MB',
    'profile.backgroundHelp': 'Background for the staff contact form splash screen',
    'profile.language': 'Language Preference',
    'profile.selectLanguage': 'Select Language',
    'profile.uploading': 'Uploading...',
    'profile.saving': 'Saving...',
    'profile.updated': 'Profile updated successfully!',
    'profile.updateError': 'Failed to update profile',
    'profile.fillRequired': 'Please fill in all required fields',
    'profile.passwordSection': 'Change Password',
    'profile.passwordSectionDesc': 'Update your account password',
    'profile.currentPassword': 'Current Password',
    'profile.currentPasswordPlaceholder': 'Enter your current password',
    'profile.newPassword': 'New Password',
    'profile.newPasswordPlaceholder': 'Enter new password (minimum 6 characters)',
    'profile.confirmPassword': 'Confirm New Password',
    'profile.confirmPasswordPlaceholder': 'Confirm your new password',
    'profile.changePasswordButton': 'Change Password',
    'profile.changingPassword': 'Changing Password...',
    'profile.passwordChanged': 'Password changed successfully!',
    'profile.passwordChangeError': 'Failed to change password',
    'profile.passwordMismatch': 'Passwords do not match',
    'profile.passwordTooShort': 'Password must be at least 6 characters',
    'profile.fillPasswordFields': 'Please fill in all password fields',
    'profile.accountInfo': 'Account Information',
    'profile.accountType': 'Account Type:',
    'profile.accountOwner': 'Account Owner',
    'profile.company': 'Company:',
    'profile.notSet': 'Not set',
    'profile.userId': 'User ID:',
    'profile.languageNote': 'The selected language will be applied to all contact forms used by your staff workers. This ensures consistency in data collection across your team.',
    
    // Common
    'common.logout': 'Logout',
    'common.poweredBy': 'Powered by',
    'common.language': 'Language',
    'common.english': 'English',
    'common.french': 'French',
    'common.loading': 'Loading',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.optional': 'Optionnel',
    'common.adding': 'Ajout en cours...',
    'common.saving': 'Enregistrement...',
    'common.deleting': 'Suppression...',
  },
  fr: {
    // Staff Contact Form
    'form.title': 'Formulaire de Contact Lead',
    'form.subtitle': 'Collecter les informations des clients potentiels',
    'form.clientManager': 'Gestionnaire de Client',
    'form.clientManager.placeholder': 'Sélectionner le gestionnaire',
    'form.fullName': 'Nom Complet',
    'form.fullName.placeholder': 'Entrez le nom complet',
    'form.company': 'Entreprise / Organisation',
    'form.company.placeholder': 'Entrez le nom de l\'entreprise',
    'form.email': 'Adresse Email',
    'form.email.placeholder': 'email@exemple.com',
    'form.phone': 'Numéro de Téléphone',
    'form.phone.placeholder': '+216 XX XXX XXX',
    'form.profile': 'Profil de Contact', // NEW: Profile instead of industry
    'form.profile.placeholder': 'Sélectionner le profil', // NEW
    'form.zone': 'Zone Géographique',
    'form.zone.placeholder': 'Sélectionner la région',
    'form.interest': 'Intérêt Pendant la Visite',
    'form.interest.placeholder': 'Décrivez leurs intérêts et besoins',
    'form.comments': 'Commentaires Additionnels',
    'form.comments.placeholder': 'Toute note ou observation supplémentaire',
    'form.submit': 'Soumettre le Lead',
    'form.reset': 'Réinitialiser',
    'form.required': 'Requis',
    
    // Contact Profile Options (NEW)
    'profile.engineer': 'Ingénieur',
    'profile.administrator': 'Administrateur',
    'profile.manager': 'Manager',
    'profile.director': 'Directeur',
    'profile.ceo': 'CEO/Exécutif',
    'profile.sales': 'Ventes/Marque',
    'profile.it': 'Professionnel IT',
    'profile.hr': 'Professionnel RH',
    'profile.finance': 'Finance/Comptabilité',
    'profile.operations': 'Opérations',
    'profile.consultant': 'Consultant',
    'profile.technician': 'Technicien',
    'profile.student': 'Étudiant/Rechercheur',
    'profile.other': 'Autre',
    
    // Owner Dashboard - Navigation
    'nav.overview': 'Vue d\'Ensemble',
    'nav.workers': 'Employés',
    'nav.analytics': 'Analytiques',
    'nav.export': 'Export de Données',
    'nav.profile': 'Profil',
    'nav.loggedInAs': 'Connecté en tant que',
    
    // Owner Dashboard - Overview Page
    'overview.title': 'Vue d\'Ensemble',
    'overview.subtitle': 'Aperçu en temps réel pour',
    'overview.totalLeads': 'Total des Leads Collectés',
    'overview.totalWorkers': 'Total des Employés',
    'overview.activeWorkers': 'Employés Actifs',
    'overview.avgLeads': 'Moyenne de Leads par Employé',
    'overview.avgPerWorker': 'Moy. par Employé',
    'overview.recentLeads': 'Leads Récents',
    'overview.currentEvent': 'Événement Actuel',
    'overview.active': 'Actif',
    'overview.avg': 'Moy',
    'overview.noLeads': 'Aucun lead collecté pour cet événement',
    'overview.name': 'Nom',
    'overview.contact': 'Contact',
    'overview.company': 'Entreprise',
    'overview.phone': 'Téléphone',
    'overview.email': 'Email',
    'overview.zone': 'Zone',
    'overview.worker': 'Employé',
    'overview.date': 'Date',
    'overview.collectedBy': 'Collecté Par',
    'overview.fullName': 'Nom Complet',
    'overview.clientManager': 'Gestionnaire de Client',
    'overview.fromCurrentEvent': 'De l\'événement actuel seulement',
    
    // Workers Management
    'workers.title': 'Gestion des Employés',
    'workers.subtitle': 'Gérer vos employés et leur accès',
    'workers.addWorker': 'Ajouter Employé',
    'workers.name': 'Nom',
    'workers.email': 'Email',
    'workers.status': 'Statut',
    'workers.leads': 'leads',
    'workers.leadsCollected': 'Leads Collectés',
    'workers.actions': 'Actions',
    'workers.active': 'Actif',
    'workers.disabled': 'Désactivé',
    'workers.edit': 'Modifier',
    'workers.disable': 'Désactiver',
    'workers.enable': 'Activer',
    'workers.deleteAction': 'Supprimer',
    'workers.deleteWorker': 'Supprimer Employé',
    'workers.deleteWarning': 'Cette action ne peut être annulée',
    'workers.deleteMessage': 'Êtes-vous sûr de vouloir supprimer',
    'workers.confirmDelete': 'Supprimer Employé',
    'workers.noWorkers': 'Aucun employé',
    'workers.addWorkerTitle': 'Ajouter Employé',
    'workers.editWorkerTitle': 'Modifier Employé',
    'workers.password': 'Mot de Passe',
    'workers.confirmPassword': 'Confirmer Mot de Passe',
    'workers.createWorker': 'Créer Employé',
    'workers.updateWorker': 'Mettre à Jour',
    'workers.cancel': 'Annuler',
    'workers.totalWorkers': 'Total des Employés',
    'workers.activeWorkers': 'Employés Actifs',
    'workers.disabledWorkers': 'Employés Désactivés',
    'workers.fullName': 'Nom Complet',
    'workers.emailHelp': 'Laissez vide pour permettre la connexion avec le nom uniquement',
    'workers.errorLoading': 'Échec du chargement des employés',
    'workers.workerAdded': 'Employé ajouté avec succès !',
    'workers.errorAdding': 'Échec de l\'ajout de l\'employé',
    'workers.workerDisabled': 'Employé désactivé',
    'workers.workerEnabled': 'Employé activé',
    'workers.errorUpdating': 'Échec de la mise à jour du statut de l\'employé',
    'workers.workerUpdated': 'Employé mis à jour avec succès !',
    'workers.workerDeleted': 'Employé supprimé avec succès !',
    'workers.errorDeleting': 'Échec de la suppression de l\'employé',
    'workers.editWorker': 'Modifier Employé',
    'workers.newPassword': 'Nouveau Mot de Passe',
    'workers.emailChangeNote': 'Laissez vide pour conserver l\'email actuel',
    'workers.passwordChangeNote': 'Laissez vide pour conserver le mot de passe actuel',
    'workers.saveChanges': 'Enregistrer',
    
    // Analytics
    'analytics.title': 'Analytiques',
    'analytics.subtitle': 'Métriques de performance et statistiques',
    'analytics.leadsOverTime': 'Leads Collectés au Fil du Temps',
    'analytics.noData': 'Aucune donnée disponible. Commencez à collecter des leads !',
    'analytics.topPerformers': 'Meilleurs Employés',
    'analytics.active': 'Actif',
    'analytics.disabled': 'Désactivé',
    'analytics.leadsCollected': 'leads',
    'analytics.noWorkers': 'Aucun employé. Ajoutez des employés pour voir les performances.',
    'analytics.leadsPerWorker': 'Leads par Employé',
    'analytics.activeOnly': 'Employés actifs uniquement',
    'analytics.leaderboard': 'Classement des Employés',
    'analytics.topPerformer': 'Meilleur Performeur',
    'analytics.totalActiveWorkers': 'Total Employés Actifs',
    'analytics.averagePerformance': 'Performance Moyenne',
    'analytics.currentlyActive': 'Actuellement actifs',
    'analytics.leadsPerWorkerMetric': 'Leads par employé',
    'analytics.noActiveWorkers': 'Aucun employé actif',
    
    // Data Export
    'export.title': 'Export de Données',
    'export.subtitle': 'Télécharger vos données de leads en format CSV',
    'export.exportAll': 'Exporter Tous les Leads',
    'export.downloadAll': 'Tout Télécharger',
    'export.exportAllDesc': 'Télécharger tous les leads collectés par votre personnel pour l\'événement actuel',
    'export.exportByWorker': 'Exporter par Employé',
    'export.exportByWorkerDesc': 'Filtrer et télécharger les leads collectés par un membre spécifique du personnel',
    'export.selectWorker': 'Sélectionner Employé',
    'export.allWorkers': 'Tous les Employés',
    'export.chooseWorker': 'Choisir un employé...',
    'export.export': 'Exporter',
    'export.exporting': 'Export en cours...',
    'export.downloadFiltered': 'Télécharger Données Filtrées',
    'export.currentEvent': 'Événement Actuel',
    'export.note': 'Remarque',
    'export.noteDesc': 'Les fichiers CSV incluent tous les détails des leads : informations de contact, données d\'entreprise, zone géographique, secteur d\'activité et horodatages de collecte.',
    'export.errorLoading': 'Échec du chargement des données',
    'export.allExported': 'Tous les leads exportés avec succès !',
    'export.workerExported': 'Données de l\'employé exportées avec succès !',
    'export.errorExporting': 'Échec de l\'export des données',
    'export.exportingCurrentEvent': 'Export des données de l\'événement actuel uniquement',
    'export.event': 'Événement',
    'export.csvContents': 'Contenu du Fichier CSV',
    'export.csvContentsDesc': 'Les fichiers CSV exportés incluront les colonnes suivantes:',
    'export.fullName': 'Nom Complet',
    'export.companyOrg': 'Entreprise / Organisation',
    'export.emailAddress': 'Adresse Email',
    'export.phoneNumber': 'Numéro de Téléphone',
    'export.industrySector': 'Secteur d\'Activité',
    'export.geographicZone': 'Zone Géographique',
    'export.clientManager': 'Gestionnaire de Client',
    'export.interestDuringVisit': 'Intérêt Pendant la Visite',
    'export.comments': 'Commentaires',
    'export.collectedByWorker': 'Collecté Par (Employé)',
    'export.collectionDateTime': 'Date & Heure de Collecte',
    'export.historicalData': 'Accès aux Données Historiques',
    'export.historicalDataDesc': 'Vous ne pouvez exporter que les données de l\'événement actuel. Les données historiques des événements précédents sont archivées et accessibles uniquement aux Super Administrateurs.',
    'export.leads': 'leads',
    
    // Profile/Settings
    'profile.title': 'Paramètres du Profil',
    'profile.subtitle': 'Gérer vos paramètres de compte et préférences',
    'profile.languageSettings': 'Paramètres de Langue',
    'profile.languageDescription': 'Choisissez la langue pour votre tableau de bord et formulaires de contact',
    'profile.personalInfo': 'Informations Personnelles',
    'profile.personalInfoDescription': 'Mettre à jour vos détails de compte',
    'profile.fullName': 'Nom Complet',
    'profile.email': 'Adresse Email',
    'profile.emailAddress': 'Adresse Email',
    'profile.emailNote': 'L\'email ne peut pas être modifié',
    'profile.changePassword': 'Changer le Mot de Passe (Optionnel)',
    'profile.newPassword': 'Nouveau Mot de Passe',
    'profile.confirmNewPassword': 'Confirmer le Nouveau Mot de Passe',
    'profile.leaveBlankPassword': 'Laissez vide pour conserver le mot de passe actuel',
    'profile.confirmPasswordPlaceholder': 'Confirmer le nouveau mot de passe',
    'profile.saveChanges': 'Enregistrer',
    'profile.companyInfo': 'Informations de l\'Entreprise',
    'profile.companyName': 'Nom de l\'Entreprise',
    'profile.companyBranding': 'Branding de l\'Entreprise',
    'profile.companyBrandingDescription': 'Personnalisez le logo de votre entreprise (apparaît sur les formulaires de contact du personnel)',
    'profile.companyLogo': 'Logo de l\'entreprise',
    'profile.companyBackground': 'Arrière-plan du formulaire de contact',
    'profile.noLogoUploaded': 'Aucun logo téléchargé',
    'profile.noBackgroundUploaded': 'Aucun arrière-plan téléchargé',
    'profile.uploadCompanyLogo': 'Télécharger le logo de l\'entreprise',
    'profile.uploadBackground': 'Télécharger l\'image d\'arrière-plan',
    'profile.logoRecommendation': 'Recommandé : image carrée, minimum 200x200px, format JPG/PNG/WebP, max 5 Mo',
    'profile.logoHelp': 'Ce logo apparaîtra sur l\'écran d\'accueil du formulaire de contact du personnel',
    'profile.backgroundRecommendation': 'Recommandé : 1920x1080px ou plus, format JPG/PNG/WebP, max 5 Mo',
    'profile.backgroundHelp': 'Arrière-plan pour l\'écran d\'accueil du formulaire de contact du personnel',
    'profile.language': 'Préférence de Langue',
    'profile.selectLanguage': 'Sélectionner la Langue',
    'profile.uploading': 'Téléchargement...',
    'profile.saving': 'Enregistrement...',
    'profile.updated': 'Profil mis à jour avec succès !',
    'profile.updateError': 'Échec de la mise à jour du profil',
    'profile.fillRequired': 'Veuillez remplir tous les champs obligatoires',
    'profile.passwordSection': 'Changer le Mot de Passe',
    'profile.passwordSectionDesc': 'Mettre à jour votre mot de passe',
    'profile.currentPassword': 'Mot de Passe Actuel',
    'profile.currentPasswordPlaceholder': 'Entrez votre mot de passe actuel',
    'profile.newPassword': 'Nouveau Mot de Passe',
    'profile.newPasswordPlaceholder': 'Entrez le nouveau mot de passe (minimum 6 caractères)',
    'profile.confirmPassword': 'Confirmer le Nouveau Mot de Passe',
    'profile.confirmPasswordPlaceholder': 'Confirmez votre nouveau mot de passe',
    'profile.changePasswordButton': 'Changer le Mot de Passe',
    'profile.changingPassword': 'Changement en cours...',
    'profile.passwordChanged': 'Mot de passe changé avec succès !',
    'profile.passwordChangeError': 'Échec du changement de mot de passe',
    'profile.passwordMismatch': 'Les mots de passe ne correspondent pas',
    'profile.passwordTooShort': 'Le mot de passe doit contenir au moins 6 caractères',
    'profile.fillPasswordFields': 'Veuillez remplir tous les champs de mot de passe',
    'profile.accountInfo': 'Informations du compte',
    'profile.accountType': 'Type de Compte:',
    'profile.accountOwner': 'Propriétaire du Compte',
    'profile.company': 'Entreprise:',
    'profile.notSet': 'Non défini',
    'profile.userId': 'ID Utilisateur:',
    'profile.languageNote': 'La langue sélectionnée sera appliquée à tous les formulaires de contact utilisés par vos employés. Cela garantit la cohérence dans la collecte de données au sein de votre équipe.',
    
    // Common
    'common.logout': 'Déconnexion',
    'common.poweredBy': 'Propulsé par',
    'common.language': 'Langue',
    'common.english': 'Anglais',
    'common.french': 'Français',
    'common.loading': 'Chargement',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.search': 'Rechercher',
    'common.filter': 'Filter',
    'common.optional': 'Optionnel',
    'common.adding': 'Ajout en cours...',
    'common.saving': 'Enregistrement...',
    'common.deleting': 'Suppression...',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Initialize language from localStorage or default to 'en'
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return (stored === 'en' || stored === 'fr') ? stored : 'en';
  });

  // Update localStorage whenever language changes
  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}